Update scripting for automated setup

diff --git a/script/sh/read_env b/script/sh/read_env
--- a/script/sh/read_env
+++ b/script/sh/read_env
@@ -8,8 +8,8 @@
 
 read_env() {
     if [ ! -f .env ]; then
-        echo "Error: .env file not found!" >&2
-        return 1
+        echo "==> Warning: .env file not found." >&2
+        return 0
     fi
 
     # Read .env file, ignoring comments and empty lines
